/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: famousandfaded (https://sketchfab.com/famousandfaded)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/airports-around-the-world-e58f56a352b540469fd209abf0c37bc5
Title: Airports around the world
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/airports_around_the_world.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.9}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.matairport_material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.matairport_material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.matsurface_material}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/airports_around_the_world.glb')
